//
// Created by Ethan West on 4/7/21.
//

#ifndef MPL_EWEST3_CBREMNER_MTOCONNO_FACTORING_H
#define MPL_EWEST3_CBREMNER_MTOCONNO_FACTORING_H


class Factoring {

};


#endif //MPL_EWEST3_CBREMNER_MTOCONNO_FACTORING_H
